serviceProviders:
- type: GitHub
  clientId: "94ad5237e8d345149e34"
  clientSecret: "169fedcb1c7e5956a6441d8cb5e8e8fe4fb8b87e"
- type: Quay
  clientId: "456"
  clientSecret: "54"
- type: GitLab
  clientId: "123"
  clientSecret: "42"
