apiVersion: appstudio.redhat.com/v1beta1
kind: SPIAccessTokenBinding
metadata:
  name: spi-binding-github
spec:
  repoUrl: https://github.com
  secret:
    name: spi-binding-github
    annotations:
      tekton.dev/git-0: https://github.com #!!!
    type: kubernetes.io/basic-auth
    # sa: saNameToGenerate


