apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-extra-role
rules:
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - watch
      - list
  - apiGroups:
      - appstudio.redhat.com
    resources:
      - spiaccesstokendataupdates
    verbs:
      - create